# Generated by Django 4.2.3 on 2023-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='first_name',
            field=models.CharField(default='advertisements', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
