# Generated by Django 4.2.3 on 2023-08-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0002_advertisement_first_name_alter_advertisement_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='descreption',
            new_name='description',
        ),
    ]
